

from wind_git.ctts_env_awo.ctts_env.constants import *
import numpy as np
import sys
import os
import subprocess

import re


##########################################################################################

def generate_grid_mcfost(parafile,args_sup=""):
	"""
		Generate a grid with mcfost from parafile.
		Absolute path needed.
	"""
	_mcfost_bin = "/Users/tessoreb/Documents/mcfost/src/mcfost"
	return subprocess.run(_mcfost_bin + " "+parafile+" -disk_struct "+args_sup,shell=True)
	
def _generate_grid_mcfost_fork(parafile,args_sup=""):
	"""
		Generate a grid with mcfost from parafile.
		Absolute path needed.
	"""
	_mcfost_bin = "/Users/tessoreb/Documents/codes/mcfost_fork/mcfost/src/mcfost"
	return subprocess.run(_mcfost_bin + " "+parafile+" -disk_struct "+args_sup,shell=True)
	
def compress_list(list_str,out):
	'''
	Create a folder with data
	'''
	data = ""
	for l in range(len(list_str)):
		data += list_str[l]+" "
	print(data)
	return subprocess.run("tar -zcf "+out+" "+data,shell=True)

def extract_running_time(filedotout):
	"""
		extract the running time of the code from output file.
		the time is return in hours.
	"""
	f = open(filedotout,'r')
	for line in f:
		if re.search("Processing complete in", line):
			stime = line.split()
			stime_cpu = f.readline().split()
			time = (stime[-3],stime[-2],stime[-1])
			time_cpu = (stime_cpu[-3],stime_cpu[-2],stime[-1])
			break
#     		yield time, time_cpu
	f.close()
	t1 = float(time[0][:-1]) + float(time[1][:-1])/60 + float(time[2][:-1])/3600
	t2 = float(time_cpu[0][:-1]) + float(time_cpu[1][:-1])/60 + float(time_cpu[2][:-1])/3600
# 	#convert back to hours using t in secs.
# 	import time
# 	_ = time.strftime("%H:%M:%S", time.gmtime(t1*3600))
	return t1, t2

	
def define_cells_limits(r,t,p, Rmin=1, Rmax=1000, l3d=False):
	"""
	From the cell centres, compute the cell limits
	There is one point in each direction more
	
	"""
	
	shape = r.shape
	if shape[-1] > 1:
		p_lim = np.zeros(shape[-1]+1)
	else:
		p_lim = np.zeros(1)
	r_lim = np.zeros(shape[0]+1)	
	
	jstart = 0
	jend = (shape[1],shape[1] // 2)[l3d]
	sint_lim = np.zeros(shape[1]+1) - 99 #for debug
	
	p_lim[0] = 0.0
	p_lim[-1] = 2*np.pi

	r_lim[0] = Rmin
	for i in range(1,shape[0]):
# 		r_lim[i] = 0.5*(r[i,0,0] + r[i-1,0,0])
		dr = r[i,0,0] - r[i-1,0,0]
		r_lim[i] = r_lim[i-1] + dr
	r_lim[shape[0]] = Rmax
		
	w = np.sin(t[0,:,0] - (0, np.pi/2)[l3d]) #1 to -1 if l3d
	sint_lim[jstart] = 1.0
	for j in range(jstart+1, jend):
		sint_lim[j] = (w[j-1] + w[j])*0.5
# 		dt = w[j]-w[j-1]
# 		sint_lim[j] = sint_lim[j-1] + dt
	sint_lim[jend] = 0
	if l3d:
		sint_lim[jend+1:] = -sint_lim[jstart:jend][::-1]
		cost_lim = np.sqrt(1.0 - sint_lim**2)
	t_lim = np.arcsin(sint_lim) #-pi/2 to pi/2 if l3d

	for k in range(1, shape[2]):
		p_lim[k] = 0.5*(p[0,0,k-1] + p[0,0,k])
# 		dp = p[0,0,k] - p[0,0,k-1]
# 		p_lim[k] = p_lim[k-1] + dp
	
	return r_lim, sint_lim, p_lim
	
def define_cells_centres(r_lim,sint_lim,p_lim):
	"""
	from the grid limits define a 3d grid of cell centres
	with one point less in each direction
	"""
	
	r_centres = np.sqrt(r_lim[1:] * r_lim[:-1]) #try the other
# 	r_centres = 0.5 * (r_lim[1:] + r_lim[:-1])
	w_centres = 0.5 * (sint_lim[1:] + sint_lim[:-1])
	uv_centres = np.sqrt(1.0 - w_centres**2)
	if p_lim.shape[0]==1:
		p_centres = [0]
	else:
		p_centres = 0.5 * (p_lim[1:] + p_lim[:-1])
		
# 	rs, ws, ps = np.meshgrid(r_centres, \
# 		0.5 * (sint_lim[1:] + sint_lim[:-1]), p_centres, indexing="ij")
# 	ts = np.arcsin(ws)	

	#we want the limits from pi/2 to -pi/2 in theta for mcfost
	#but theta must go from pi to 0 for the cell mapping.
	rs, ts, ps = np.meshgrid(r_centres, \
		np.arctan(w_centres/uv_centres) + (0, np.pi/2)[len(p_centres)>1], \
		p_centres, indexing="ij")
		
		
	return rs, ts, ps

def read_mcfost_grid(grid_file="data_disk/grid.fits.gz",vol_file="data_disk/volume.fits.gz"):
    """
		read the grid.fits.gz file generated by mcfost.
		
		Spatial units in au. Volume in au^3.
    """
    from astropy.io import fits

    G = fits.open(grid_file)[0]
    # what kind of grid are we using??
    Ndim = G.data.ndim
    if Ndim > 2:
        Nvar, nphi, nz, nr = G.shape
        if Nvar == 2:
            if nphi == 1 and nz == 1:
                mode2D = False
            else:
                mode2D = True

            mode3D = False
            mode1D = not mode2D
            Voronoi = False
            r = G.data[0]
            z = G.data[1]
            phi = np.zeros(r.shape)
        elif Nvar == 3:  # 1D mode never happens here, since if nphi > 1 not 1D
            mode3D = True
            mode2D = False
            Voronoi = False
            mode1D = False
            r = G.data[0]
            z = G.data[1]
            phi = G.data[2]
        else:
            print("Error, Nvar = %d, should be at least 2 if not Voronoi" % (Nvar))
            sys.exit()
            
        x1 = r; x2 = z; x3 = phi

    else:
        x1, x2, x3 = G.data #x,y,z
        nphi = 1
        nr = len(x1)
        nz = 1
        mode1D = False
        mode2D = False
        mode3D = False
        Voronoi = True

    Ncells = nphi * nr * nz

    if Ncells > 1e6:
        print(" -- Grid has %.3f million cells"%(float(Ncells)*1e-6))
    else:
        print(" -- Grid has %d cells" % Ncells)

    if mode1D:
        geom = "1d"
    elif mode2D:
        geom = "2d"
    elif mode3D:
        geom = "3d"
    elif Voronoi:
        geom = "voronoi"
    else:
        print("Geometry unknown!")
        exit()
        
    vol = fits.open(vol_file)[0].data #AU^3
    h = (1/3)*(vol)**(1/3) #au
    grid = {"x1":x1,"x2":x2,"x3":x3,"geom":geom,"NR":nr,"Nz":nz,"Nphi":nphi,"shape":x1.shape,"V":vol,"h":h}


    return grid